name: workout_demo_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  connectivity_plus: ^4.0.2
  dio: ^5.3.2
  fade_shimmer: ^2.2.0
  flutter:
    sdk: flutter
  fluttertoast: ^8.2.2
  get: ^4.6.5
  google_fonts: ^5.1.0
  sizer_pro: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/
